
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 
	#The name of the modpack
	modpackName = "F&TS Reboot"
	#The version of the modpack
	modpackVersion = "v1.00"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

